
package Vistas;

public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mniAgregarCliente = new javax.swing.JMenuItem();
        mniBuscarCliente = new javax.swing.JMenuItem();
        mniBorrarCliente = new javax.swing.JMenuItem();
        mnuDirectorio = new javax.swing.JMenu();
        mniBuscarPorCiudad = new javax.swing.JMenuItem();
        mniBuscarPorApellido = new javax.swing.JMenuItem();
        mnuCiudades = new javax.swing.JMenu();
        mniAgregarCiudad = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mitemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        escritorio.setName(""); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        mnuClientes.setText("Clientes");

        mniAgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniAgregarCliente.setText("Agregar Cliente");
        mniAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mniAgregarCliente);

        mniBuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniBuscarCliente.setText("Buscar Cliente");
        mniBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mniBuscarCliente);

        mniBorrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniBorrarCliente.setText("Borrar Cliente");
        mniBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBorrarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mniBorrarCliente);

        jMenuBar1.add(mnuClientes);

        mnuDirectorio.setText("Directorio");

        mniBuscarPorCiudad.setText("Buscar Clientes por Ciudad");
        mniBuscarPorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarPorCiudadActionPerformed(evt);
            }
        });
        mnuDirectorio.add(mniBuscarPorCiudad);

        mniBuscarPorApellido.setText("Buscar Teléfono por Apellido");
        mniBuscarPorApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarPorApellidoActionPerformed(evt);
            }
        });
        mnuDirectorio.add(mniBuscarPorApellido);

        jMenuBar1.add(mnuDirectorio);

        mnuCiudades.setText("Ciudades");

        mniAgregarCiudad.setText("Agregar Ciudad");
        mniAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarCiudadActionPerformed(evt);
            }
        });
        mnuCiudades.add(mniAgregarCiudad);

        jMenuBar1.add(mnuCiudades);

        mnuSalir.setText("Salir");

        mitemSalir.setText("Salir");
        mitemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mitemSalir);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mitemSalirActionPerformed

    private void mniAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmAgregarCliente agregarCliente = new IfrmAgregarCliente();
        agregarCliente.setVisible(true);
        escritorio.add(agregarCliente);
        agregarCliente.moveToFront();
    }//GEN-LAST:event_mniAgregarClienteActionPerformed

    private void mniBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmBuscarCliente buscarCliente = new IfrmBuscarCliente();
        buscarCliente.setVisible(true);
        escritorio.add(buscarCliente);
        buscarCliente.moveToFront();
    }//GEN-LAST:event_mniBuscarClienteActionPerformed

    private void mniBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBorrarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmBorrarCliente borrarCliente = new IfrmBorrarCliente();
        borrarCliente.setVisible(true);
        escritorio.add(borrarCliente);
        borrarCliente.moveToFront();
    }//GEN-LAST:event_mniBorrarClienteActionPerformed

    private void mniBuscarPorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarPorCiudadActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmBuscarClienteCiudad buscarClienteCiudad = new IfrmBuscarClienteCiudad();
        buscarClienteCiudad.setVisible(true);
        escritorio.add(buscarClienteCiudad);
        buscarClienteCiudad.moveToFront();
    }//GEN-LAST:event_mniBuscarPorCiudadActionPerformed

    private void mniBuscarPorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarPorApellidoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmBuscarTelefonoApellido buscarTelefonoApellido = new IfrmBuscarTelefonoApellido();
        buscarTelefonoApellido.setVisible(true);
        escritorio.add(buscarTelefonoApellido);
        buscarTelefonoApellido.moveToFront();
    }//GEN-LAST:event_mniBuscarPorApellidoActionPerformed

    private void mniAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarCiudadActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        IfrmAgregarCiudad agregarCiudad = new IfrmAgregarCiudad();
        agregarCiudad.setVisible(true);
        escritorio.add(agregarCiudad);
        agregarCiudad.moveToFront();
    }//GEN-LAST:event_mniAgregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitemSalir;
    private javax.swing.JMenuItem mniAgregarCiudad;
    private javax.swing.JMenuItem mniAgregarCliente;
    private javax.swing.JMenuItem mniBorrarCliente;
    private javax.swing.JMenuItem mniBuscarCliente;
    private javax.swing.JMenuItem mniBuscarPorApellido;
    private javax.swing.JMenuItem mniBuscarPorCiudad;
    private javax.swing.JMenu mnuCiudades;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuDirectorio;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
